### ISSUE TITLE
Add explanation in "Adding nodes“ step 8

### ISSUE THREAD

**Issue by Jayanring** [ethereum-optimism/stack-docs#14]
In https://stack.optimism.io/docs/build/operations/#adding-nodes step 8: “_Start op-node (using the **same command line** you used on the initial node)_".
The command line is 
```
./bin/op-node \
	--l2=http://localhost:8551 \
	--l2.jwt-secret=./jwt.txt \    
	--sequencer.enabled \
	--sequencer.l1-confs=3 \
	--verifier.l1-confs=3 \
	--rollup.config=./rollup.json \
	--rpc.addr=0.0.0.0 \
	--rpc.port=8547 \
	--p2p.disable \
	--rpc.enable-admin \
	--p2p.sequencer.key=$SEQ_KEY \
	--l1=$L1_RPC \
	--l1.rpckind=$RPC_KIND
```
There should be only one sequencer in L2. Does `--sequencer.enabled` mean this node is sequencer? If so, will the same command line I using to add a new node run another sequencer?

**Comment by sbvegan** [comment]
Good catch, there should only be one sequencer. Adding new nodes should not include `--sequencer.enabled` or `sequencer.l1-confs`. This is fixed in https://github.com/ethereum-optimism/stack-docs/pull/26
